- unum/Makefile
- unum/files/unum.common
This should take care of MinimSecure/unum-sdk#33
> Pick lan interface with an ip in unum init

- modemrouter-support/BTN_0
> modemrouter-support: add bounce of wan interface on status up

- modemrouter-support/BTN_0
> modemrouter-support: add update of LEDs on cable modem interface status change

- web-landing/23_update_www_landing
> web-landing: fix mac address on cablemodem landing page

- ipv6-custom/99_ipv6_custom
- ipv6-custom/Makefile
> ipv6-custom: add customisations to base openwrt for ipv6

- firewall-custom/99_firewall_custom
- firewall-custom/Makefile
> firewall: add new package firewall-custom

- minim-openwifi-scripts/Makefile
- minim-openwifi-scripts/files/etc/uci-defaults/38_enable_usb_automount_config
added a configuration to enable the anon_mount to enable the usb auto mount
> added a configuration for usb auto mount in uci defaults

- ipv6-custom/99_ipv6_custom
Add firewall rules if they're not present, prevents need for factory reset
SW-2854
> ipv6-custom: fix ipv6 upgrade

- web-admin/Makefile
- web-admin/enable_sshd.html
- web-admin/mode_check
- web-admin/src/Makefile
- web-admin/src/web_admin.c
- web-admin/start_sshd.html
> r14: enable SSH by web.

- minim-openwifi-scripts/files/sbin/leds.sh
> Factory Reset

- minim-openwifi-scripts/files/sbin/leds.sh
> r14: Firmware Update LED Indication.

- common/Makefile
- modemrouter-support/Makefile
- modemrouter-support/modemrouter-mfg
> modemrouter-support: add manufacturing bridge script

- minim-openwifi-scripts/Makefile
- minim-openwifi-scripts/files/etc/uci-defaults/39_enable_usteer_config
added 39_enable_usteer_config to config the usteer for band steering feature
> minim_r14:adding 39_enable_usteer_config sw-2693

- web-landing/Makefile
> web-landing: Depend on uhttpd

- minim-openwifi-scripts/files/sbin/leds.sh
- samba-manager/files/10-samba-manager.hotplug
- samba-manager/files/samba-manager.init
> minimos: r14 USB LED indication enabled.

- minim-openwifi-scripts/files/sbin/leds.sh
modified the leds.sh script to add the Q14 WPS led reuirement
> Q14 wps leds SW-3290

- web-landing/Makefile
> web-landing: fix Makefile

- samba4/files/smb.conf.template
> samba4: disable async write to reduce ram usage

- performance-tuning/99-smp-packet-steering-minim
- performance-tuning/99-smp-packet-steering-minim-defaults
- performance-tuning/Makefile
> performance-tuning: new package

- performance-tuning/99-smp-packet-steering-minim-defaults
> performance-tuning: ensure minim config section exists prior to making changes

- minim-openwifi-scripts/files/sbin/update_leds.sh
Use sysfs to determine the root bridge port so that we can update the online led appropriately based on whether we are connected via ethernet or wireless.  The list of ethernet ports to check can be defined on a per board basis.
SW-3697
> update_leds: Determine repeater connection type

- samba-manager/files/samba-manager.init
> samba-manager: change to adduser/deluser for passwd file updates

- minim-openwifi-scripts/files/sbin/update_leds.sh
> minim-openwifi-scripts: change root port determination in update_leds.sh

- web-landing-modemrouter/24_update_www_landing
- web-landing/32_update_www_landing
> web-landing: further steps to ensure page is properly regenerated
